spring:
    application:
        name: estoque
    data:
        mongodb:
            database: estoque
            authentication-database: admin
            uri: mongodb://mongodb:1412@localhost:27017/
server:
    port: 0
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka