spring:
    application:
        name: cliente
    datasource:
        url: jdbc:postgresql://localhost:5432/cliente
        username: postgres
        password: 1412
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        generate-ddl: true
server:
    port: 53792
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka