spring:
    application:
        name: venda
    datasource:
        url: jdbc:postgresql://localhost:5432/venda
        username: postgres
        password: 1412
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop
        generate-ddl: true
server:
    port: 8083
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka